#!/bin/bash -e

if [ "$TRAVIS_BRANCH" != "dev" ]; then 
    exit 0;
fi

export GIT_COMMITTER_EMAIL="jkbdiaz@gmail.com"
export GIT_COMMITTER_NAME="Jean Benitez"

git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* || exit
git fetch --all || exit

printf 'Checking out %s\n' "$BRANCH_TO_MERGE_INTO" >&2
git checkout "$BRANCH_TO_MERGE_INTO"

printf 'Merging %s\n' "$TRAVIS_COMMIT" >&2
git merge --no-ff "$TRAVIS_COMMIT" || exit

printf 'Pushing to %s\n' "$GITHUB_REPO" >&2
push_uri="https://$GITHUB_SECRET_TOKEN@github.com/$GITHUB_REPO"

# Redirect to /dev/null to avoid secret leakage
git push "$push_uri" "$BRANCH_TO_MERGE_INTO" >/dev/null 2>&1
git push "$push_uri" :"$TRAVIS_BRANCH" >/dev/null 2>&1
